/* The Voice Express Stand -- a static, data-driven reading room.
   Fetches config.json (hand-edited: brand + pay rails + Apps Script URL) and
   catalog.json (generated by librarize.py). Everything else -- the shelf, the
   full-screen reader, pay-what-you-want with copyable links + QR, passwordless
   shelves, download/read/message history -- runs client-side. The Apps Script
   web app is the only backend, reached over JSONP so no CORS setup is needed. */
(function () {
  "use strict";

  /* ── tiny dom helpers ── */
  var $ = function (s, r) { return (r || document).querySelector(s); };
  function el(t, c, txt) { var e = document.createElement(t); if (c) e.className = c; if (txt != null) e.textContent = txt; return e; }
  /* offline QR -> SVG data-URI (qr.js, no network). px arg kept for call-site parity. */
  function qr(data) {
    try {
      var q = qrcode(0, "M"); q.addData(data); q.make();
      return "data:image/svg+xml," + encodeURIComponent(q.createSvgTag(4, 8));
    } catch (e) { return ""; }
  }

  /* state filled in once the two JSON files land */
  var CFG, PAY, API, CUR, BRAND, CAT, SECTIONS, BY_ID = {}, SECLABEL = {};
  var TYPE = { gazette: "Gazette", broadsheet: "Broadsheet", compilation: "Compilation",
    booklet: "Booklet", epub: "ePub", pdf: "PDF", magazine_pdf: "Magazine", magazine_html: "eMag" };
  var SYM = { INR: "₹", USD: "$", EUR: "€", GBP: "£" };

  /* ── boot: load data, then wire the app ── */
  Promise.all([
    fetch("config.json").then(function (r) { return r.json(); }).catch(function () { return {}; }),
    fetch("catalog.json").then(function (r) { return r.json(); })
  ]).then(function (res) {
    CFG = res[0] || {}; var data = res[1] || {};
    PAY = CFG.pay || {}; API = CFG.api || "";
    BRAND = CFG.brand || "The Voice Express";
    CUR = SYM[CFG.currency] || "";
    CAT = data.catalog || [];
    SECTIONS = data.sections || [];
    SECTIONS.forEach(function (s) { SECLABEL[s.key] = s.label; });
    CAT.forEach(function (x) {
      BY_ID[x.id] = x;
      x._idx = (x.title + " " + (x.subtitle || "") + " " + (x.author || "") + " " +
        (x.tags || []).join(" ") + " " + (TYPE[x.type] || x.type) + " " +
        (SECLABEL[x.section] || "") + " " + (x.year || "")).toLowerCase();
    });
    if (CFG.logo) $("#brand-logo").src = CFG.logo;
    if (CFG.brand) $(".brand-txt").innerHTML = esc(CFG.brand) + " <em>Stand</em>";
    init(data.generated || "");
  }).catch(function (err) {
    $("#app").innerHTML = "";
    $("#app").appendChild(el("p", "empty",
      "Could not load the catalogue. Run python librarize.py, and open this over a server (or GitHub Pages) so the JSON can be fetched."));
    console.error(err);
  });

  function esc(s) { return (s || "").replace(/[<>&]/g, function (m) { return { "<": "&lt;", ">": "&gt;", "&": "&amp;" }[m]; }); }

  /* ── session + local history ── */
  var USER = localStorage.getItem("ve_user") || "";
  var LIB, DLS, READS;
  function uk(p) { return p + (USER || "anon"); }
  function loadSet(k) { try { return new Set(JSON.parse(localStorage.getItem(k) || "[]")); } catch (e) { return new Set(); } }
  function loadArr(k) { try { return JSON.parse(localStorage.getItem(k) || "[]"); } catch (e) { return []; } }
  function loadMap(k) { try { return JSON.parse(localStorage.getItem(k) || "{}"); } catch (e) { return {}; } }
  function persistLib() {
    localStorage.setItem(uk("ve_lib_"), JSON.stringify(Array.from(LIB)));
    if (USER && API) jsonp({ action: "savelib", username: USER, library: JSON.stringify(Array.from(LIB)) }).catch(function () {});
  }

  /* ── JSONP to the Apps Script (reads + writes, CORS-free) ── */
  function jsonp(params) {
    return new Promise(function (res, rej) {
      if (!API) { rej("noapi"); return; }
      var cb = "ve_cb_" + Math.random().toString(36).slice(2);
      var s = document.createElement("script");
      var to = setTimeout(function () { cleanup(); rej("timeout"); }, 12000);
      function cleanup() { clearTimeout(to); try { delete window[cb]; } catch (e) {} s.remove(); }
      window[cb] = function (d) { cleanup(); res(d); };
      params.callback = cb;
      s.src = API + (API.indexOf("?") > -1 ? "&" : "?") + new URLSearchParams(params).toString();
      s.onerror = function () { cleanup(); rej("neterr"); };
      document.head.appendChild(s);
    });
  }

  /* ── search ── */
  function search(q) {
    var terms = q.toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) return [];
    return CAT.map(function (x) {
      var score = 0, tl = x.title.toLowerCase();
      for (var i = 0; i < terms.length; i++) {
        var t = terms[i];
        if (x._idx.indexOf(t) === -1) return { x: x, score: -1 };
        score += tl.indexOf(t) === 0 ? 5 : tl.indexOf(t) > -1 ? 3 : 1;
      }
      return { x: x, score: score };
    }).filter(function (r) { return r.score > 0; })
      .sort(function (a, b) { return b.score - a.score || (b.x.date || "").localeCompare(a.x.date || ""); })
      .map(function (r) { return r.x; });
  }

  /* ── reveal-on-scroll ── */
  var io = ("IntersectionObserver" in window) ? new IntersectionObserver(function (es) {
    es.forEach(function (e) { if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); } });
  }, { rootMargin: "0px 0px -8% 0px" }) : null;
  function reveal(n) { if (io) { n.classList.add("reveal"); io.observe(n); } }

  /* ── card ── */
  function card(x) {
    var c = el("article", "card");
    var cov = el("div", "cover");
    if (x.cover) { var im = el("img"); im.loading = "lazy"; im.src = x.cover; im.alt = ""; cov.appendChild(im); }
    cov.appendChild(el("span", "badge", TYPE[x.type] || x.type));
    var bm = el("button", "bookmark" + (LIB.has(x.id) ? " on" : ""), LIB.has(x.id) ? "★" : "☆");
    bm.title = "Save to your library";
    bm.onclick = function (ev) { ev.stopPropagation(); toggleSave(x, bm); };
    cov.appendChild(bm);
    var hint = el("div", "read-hint"); hint.appendChild(el("span", null, "Read")); cov.appendChild(hint);
    cov.onclick = function () { openReader(x); };
    c.appendChild(cov);
    var b = el("div", "card-b");
    var t = el("h3", "card-t", x.title); t.onclick = function () { openModal(x); }; b.appendChild(t);
    if (x.subtitle) b.appendChild(el("p", "card-s", x.subtitle));
    var m = el("div", "card-m");
    m.appendChild(el("span", "date", (x.date || "").slice(0, 10)));
    m.appendChild(el("span", "ext", (x.ext || "").toUpperCase()));
    b.appendChild(m);
    var g = el("button", "get", "Read · Get"); g.onclick = function () { openModal(x); }; b.appendChild(g);
    c.appendChild(b);
    return c;
  }
  function grid(items) { var g = el("div", "grid"); items.forEach(function (x) { g.appendChild(card(x)); }); return g; }

  function row(title, items, seeAll) {
    if (!items.length) return null;
    var wrap = el("section", "row");
    var h = el("div", "row-head");
    h.appendChild(el("h2", null, title));
    h.appendChild(el("span", "ln"));
    if (seeAll) { var sa = el("span", "seeall", "See all"); sa.onclick = function () { go(seeAll); }; h.appendChild(sa); }
    wrap.appendChild(h);
    var rw = el("div", "row-wrap"), sc = el("div", "row-scroll");
    items.forEach(function (x) { sc.appendChild(card(x)); });
    var prev = el("button", "row-nav prev", "‹"), next = el("button", "row-nav next", "›");
    prev.onclick = function () { sc.scrollBy({ left: -sc.clientWidth * 0.8, behavior: "smooth" }); };
    next.onclick = function () { sc.scrollBy({ left: sc.clientWidth * 0.8, behavior: "smooth" }); };
    rw.appendChild(prev); rw.appendChild(sc); rw.appendChild(next);
    wrap.appendChild(rw); reveal(wrap);
    return wrap;
  }

  /* ── views ── */
  var app;
  function setView(node) { app.innerHTML = ""; app.appendChild(node); window.scrollTo({ top: 0 }); }
  function byDate(a, b) { return (b.date || "").localeCompare(a.date || ""); }
  function wrapFrag(f) { var d = el("div"); d.appendChild(f); return d; }
  function headLine(title, sub) {
    var h = el("div", "sec-head");
    h.appendChild(el("h2", null, title));
    if (sub) h.appendChild(el("span", "count", sub));
    h.appendChild(el("span", "ln"));
    return h;
  }
  function countBy(list, key) { var o = {}; list.forEach(function (x) { var v = x[key]; if (v) o[v] = (o[v] || 0) + 1; }); return o; }

  function viewHome() {
    var f = document.createDocumentFragment();
    var hero = el("div", "hero");
    hero.appendChild(el("div", "kick", "Free to read · Pay what you will"));
    hero.appendChild(el("h1", null, "The Reading Room"));
    hero.appendChild(el("p", "sub", "Every gazette, broadsheet, booklet and magazine " + BRAND + " has set in type — gathered, indexed, and yours to read."));
    hero.appendChild(el("div", "stat", CAT.length + " publications  ·  " + SECTIONS.length + " collections"));
    f.appendChild(hero);

    var cont = continueReading();
    if (cont.length) { var rc = row("Continue reading", cont, null); if (rc) f.appendChild(rc); }
    var newest = CAT.slice().sort(byDate).slice(0, 12);
    var r0 = row("New arrivals", newest, "#/browse"); if (r0) f.appendChild(r0);
    SECTIONS.forEach(function (s) {
      var items = CAT.filter(function (x) { return x.section === s.key; }).sort(byDate).slice(0, 14);
      var r = row(s.label, items, "#/browse/" + s.key); if (r) f.appendChild(r);
    });
    setView(wrapFrag(f));
  }

  function viewBrowse(section) {
    var state = { section: section || "", type: "", year: "", sort: "new" };
    var box = el("div");
    box.appendChild(headLine(section ? SECLABEL[section] || "Browse" : "Browse the stand", section ? "" : "The full index"));
    var layout = el("div", "browse"), facets = el("aside", "facets"), main = el("div");
    layout.appendChild(facets); layout.appendChild(main); box.appendChild(layout);
    function base() { return state.section ? CAT.filter(function (x) { return x.section === state.section; }) : CAT.slice(); }
    function apply() {
      var list = base();
      if (state.type) list = list.filter(function (x) { return x.type === state.type; });
      if (state.year) list = list.filter(function (x) { return x.year === state.year; });
      list.sort(state.sort === "az" ? function (a, b) { return a.title.localeCompare(b.title); }
        : state.sort === "old" ? function (a, b) { return (a.date || "").localeCompare(b.date || ""); } : byDate);
      drawFacets(); drawMain(list);
    }
    function drawFacets() {
      facets.innerHTML = "";
      if (!section) facets.appendChild(facetGroup("Collection", SECTIONS.map(function (s) { return [s.key, s.label]; }),
        "section", state.section, CAT, function (x, v) { return x.section === v; }));
      var b = base();
      facets.appendChild(facetGroup("Format", Object.keys(countBy(b, "type")).map(function (t) { return [t, TYPE[t] || t]; }),
        "type", state.type, b, function (x, v) { return x.type === v; }));
      facets.appendChild(facetGroup("Year", Object.keys(countBy(b, "year")).sort().reverse().map(function (y) { return [y, y]; }),
        "year", state.year, b, function (x, v) { return x.year === v; }));
    }
    function facetGroup(title, opts, key, cur, pool, match) {
      var g = el("div", "facet"); g.appendChild(el("h4", null, title));
      opts.forEach(function (o) {
        var n = pool.filter(function (x) { return match(x, o[0]); }).length;
        if (!n) return;
        var b = el("button", cur === o[0] ? "on" : null);
        b.appendChild(el("span", null, o[1])); b.appendChild(el("span", "n", String(n)));
        b.onclick = function () {
          if (key === "section") { state.section = state.section === o[0] ? "" : o[0]; state.type = ""; state.year = ""; }
          else state[key] = state[key] === o[0] ? "" : o[0];
          apply();
        };
        g.appendChild(b);
      });
      return g;
    }
    function drawMain(list) {
      main.innerHTML = "";
      var bar = el("div", "results-bar");
      bar.appendChild(el("span", "rcount", list.length + (list.length === 1 ? " title" : " titles")));
      var sel = el("select", "sortsel");
      [["new", "Newest first"], ["old", "Oldest first"], ["az", "Title A–Z"]].forEach(function (o) {
        var op = el("option", null, o[1]); op.value = o[0]; if (o[0] === state.sort) op.selected = true; sel.appendChild(op);
      });
      sel.onchange = function () { state.sort = sel.value; apply(); };
      bar.appendChild(sel); main.appendChild(bar);
      var active = el("div", "activef");
      [["type", TYPE[state.type] || state.type], ["year", state.year]].forEach(function (p) {
        if (!state[p[0]]) return;
        var t = el("span", "ftag", p[1] + "  ×"); t.onclick = function () { state[p[0]] = ""; apply(); };
        active.appendChild(t);
      });
      main.appendChild(active);
      main.appendChild(list.length ? grid(list) : el("p", "empty", "Nothing matches those filters."));
    }
    apply(); setView(box);
  }

  function viewSearch(q) {
    var box = el("div");
    box.appendChild(headLine("Search", q ? "“" + q + "”" : ""));
    var res = q ? search(q) : [];
    var bar = el("div", "results-bar");
    bar.appendChild(el("span", "rcount", q ? (res.length + " result" + (res.length === 1 ? "" : "s")) : "Type to search the whole stand"));
    box.appendChild(bar);
    box.appendChild(res.length ? grid(res) : el("p", "empty", q ? "Nothing found. Try a title, author, tag or year." : ""));
    setView(box);
  }

  function viewLibrary() {
    var box = el("div");
    box.appendChild(headLine("My Library", USER ? "@" + USER : "a private shelf"));
    var items = Array.from(LIB).map(function (id) { return BY_ID[id]; }).filter(Boolean).sort(byDate);
    if (!items.length) {
      var e = el("div", "empty");
      e.appendChild(document.createTextNode("Tap the star on any cover to save it to your shelf."));
      var cta = el("button", "btn-dl", USER ? "Browse the stand" : "Create an account");
      cta.onclick = function () { USER ? go("#/browse") : openAcct("up"); };
      e.appendChild(el("br")); e.appendChild(cta); box.appendChild(e);
    } else {
      box.appendChild(el("div", "results-bar")).appendChild(el("span", "rcount", items.length + " saved"));
      box.appendChild(grid(items));
    }
    setView(box);
  }

  function viewDownloads() {
    var box = el("div");
    box.appendChild(headLine("My Downloads", "kept on this device" + (USER ? " · logged as @" + USER : "")));
    var seen = {}, items = [];
    DLS.slice().reverse().forEach(function (d) { if (!seen[d.id] && BY_ID[d.id]) { seen[d.id] = 1; items.push(BY_ID[d.id]); } });
    if (!items.length) box.appendChild(el("p", "empty", "Nothing downloaded yet. Open a book and hit Download to keep it here."));
    else { box.appendChild(el("div", "results-bar")).appendChild(el("span", "rcount", items.length + " downloaded")); box.appendChild(grid(items)); }
    setView(box);
  }

  function continueReading() {
    return Object.keys(READS).map(function (id) { return [id, READS[id]]; })
      .sort(function (a, b) { return b[1] - a[1]; }).slice(0, 12)
      .map(function (p) { return BY_ID[p[0]]; }).filter(Boolean);
  }

  /* ── save-to-library ── */
  function toggleSave(x, btn) {
    if (LIB.has(x.id)) LIB.delete(x.id); else LIB.add(x.id);
    persistLib();
    var on = LIB.has(x.id);
    if (btn) { btn.classList.toggle("on", on); btn.textContent = on ? "★" : "☆"; }
    renderAcct();
    if (location.hash.indexOf("#/library") === 0) viewLibrary();
    toast(on ? "Saved to your library" : "Removed from library");
  }

  /* ── reader ── */
  var rdItem = null, rdFrame = null, rdScrollHandler = null;
  var stage = function () { return $("#rd-stage"); };
  function setReaderTheme(t) {
    var s = stage(); s.className = "rd-stage theme-" + t;
    Array.prototype.forEach.call($("#rd-themes").children, function (b) { b.classList.toggle("on", b.dataset.theme === t); });
    localStorage.setItem("ve_reader_theme", t);
  }
  function openReader(x) {
    rdItem = x;
    $("#rd-type").textContent = TYPE[x.type] || x.type;
    $("#rd-title").textContent = x.title;
    syncReaderSave();
    var st = stage(); st.innerHTML = ""; $("#rd-progbar").style.width = "0";
    if (x.ext === "epub") {
      var fb = el("div", "rd-fallback");
      fb.appendChild(document.createTextNode("ePub books read best in a dedicated reader."));
      var b = el("button", "btn-dl", "Download the ePub"); b.style.maxWidth = "260px";
      b.onclick = function () { downloadItem(x); }; fb.appendChild(b); st.appendChild(fb);
    } else {
      var f = document.createElement("iframe");
      f.src = x.url; f.title = x.title;
      f.onload = function () { hookProgress(f); };
      st.appendChild(f); rdFrame = f;
    }
    setReaderTheme(localStorage.getItem("ve_reader_theme") || "paper");
    READS[x.id] = Date.now(); localStorage.setItem(uk("ve_reads_"), JSON.stringify(READS));
    logEvent("read", x, 0);
    $("#reader").hidden = false; document.body.style.overflow = "hidden";
  }
  function hookProgress(f) {
    try {
      var w = f.contentWindow, d = f.contentDocument; if (!w || !d) return;
      if (rdScrollHandler) try { w.removeEventListener("scroll", rdScrollHandler); } catch (e) {}
      rdScrollHandler = function () {
        var max = (d.documentElement.scrollHeight || 0) - w.innerHeight;
        var p = max > 0 ? Math.min(100, Math.max(0, (w.scrollY / max) * 100)) : 100;
        $("#rd-progbar").style.width = p + "%";
      };
      w.addEventListener("scroll", rdScrollHandler, { passive: true }); rdScrollHandler();
    } catch (e) { /* cross-origin would land here; same-origin so unlikely */ }
  }
  function closeReader() {
    $("#reader").hidden = true; document.body.style.overflow = "";
    stage().innerHTML = ""; rdFrame = null; rdItem = null;
  }
  function syncReaderSave() {
    var b = $("#rd-save"), on = rdItem && LIB.has(rdItem.id);
    b.classList.toggle("on", !!on); b.innerHTML = on ? "★" : "☆";
  }
  $("#rd-back").onclick = closeReader;
  $("#rd-save").onclick = function () { if (rdItem) { toggleSave(rdItem); syncReaderSave(); } };
  $("#rd-dl").onclick = function () { if (rdItem) downloadItem(rdItem); };
  $("#rd-support").onclick = function () { if (rdItem) openPay(rdItem); };
  Array.prototype.forEach.call($("#rd-themes").children, function (b) {
    b.onclick = function () { setReaderTheme(b.dataset.theme); };
  });

  /* ── detail modal ── */
  var modalItem = null;
  function openModal(x) {
    modalItem = x;
    $("#m-cover").src = x.cover || "";
    $("#m-type").textContent = TYPE[x.type] || x.type;
    $("#m-title").textContent = x.title;
    $("#m-sub").textContent = x.subtitle || "";
    var tg = $("#m-tags"); tg.innerHTML = "";
    (x.tags || []).slice(0, 8).forEach(function (t) { tg.appendChild(el("span", null, t)); });
    syncModalSave();
    $("#modal").hidden = false;
  }
  function closeModal() { $("#modal").hidden = true; modalItem = null; }
  function syncModalSave() {
    var b = $("#m-save"), on = modalItem && LIB.has(modalItem.id);
    b.classList.toggle("on", !!on); b.innerHTML = on ? "★" : "☆";
  }
  $("#modal-x").onclick = closeModal;
  $("#modal").addEventListener("click", function (e) { if (e.target.id === "modal") closeModal(); });
  $("#m-read").onclick = function () { if (modalItem) { var x = modalItem; closeModal(); openReader(x); } };
  $("#m-download").onclick = function () { if (modalItem) downloadItem(modalItem); };
  $("#m-save").onclick = function () { if (modalItem) { toggleSave(modalItem); syncModalSave(); } };
  $("#m-supporttoggle").onclick = function () { if (modalItem) openPay(modalItem); };

  /* ── download ── */
  function downloadItem(x) {
    var a = document.createElement("a"); a.href = x.url; a.download = x.file; a.target = "_blank"; a.rel = "noopener";
    document.body.appendChild(a); a.click(); a.remove();
    DLS.push({ id: x.id, file: x.file, title: x.title, t: new Date().toISOString() });
    localStorage.setItem(uk("ve_dls_"), JSON.stringify(DLS));
    logEvent("download", x, 0);
    toast("Downloading — " + x.title);
  }

  /* ── pay sheet (links + QR) ── */
  var payItem = null;
  function openPay(x) {
    payItem = x;
    $("#pay-sub").textContent = x ? "For “" + x.title + "” — name your price, then scan or tap." : "Name your price, then scan or tap.";
    $("#p-cur").textContent = CUR;
    var amt = $("#p-amt"); amt.value = (x && x.price_sugg) || 0; amt.min = (x && x.price_min) || 0;
    buildPayChips(x);
    amt.oninput = function () { renderRails(); };
    renderRails(); buildPayFoot();
    $("#pay").hidden = false;
  }
  function closePay() { $("#pay").hidden = true; payItem = null; }
  function payAmount() { return Math.max(0, +($("#p-amt").value) || 0); }
  function buildPayChips(x) {
    var box = $("#p-chips"); box.innerHTML = "";
    var opts = [{ l: "Free", v: 0 }, { l: CUR + "50", v: 50 }, { l: CUR + "100", v: 100 }, { l: CUR + "250", v: 250 }];
    if (x && x.price_sugg) opts.push({ l: "Suggested " + CUR + x.price_sugg, v: x.price_sugg });
    opts.forEach(function (o) {
      var c = el("button", "chip", o.l);
      c.onclick = function () { $("#p-amt").value = o.v; renderRails(); };
      box.appendChild(c);
    });
  }
  /* every enabled rail -> {label, url(open), qr(scan)} */
  function rails() {
    var a = payAmount(), title = payItem ? payItem.title : BRAND, out = [];
    (PAY.kofi || []).forEach(function (k) {
      if (k && k.url) out.push({ label: k.label || "Ko-fi", url: k.url, qr: k.url });
    });
    if (PAY.upi) {
      var uri = "upi://pay?pa=" + encodeURIComponent(PAY.upi) + "&pn=" + encodeURIComponent(BRAND) +
        (a ? "&am=" + a : "") + "&cu=" + (CFG.currency || "INR") + "&tn=" + encodeURIComponent(title);
      out.push({ label: "UPI · " + PAY.upi, url: uri, qr: uri, show: PAY.upi });
    }
    if (PAY.paypal) {
      var pp = PAY.paypal;
      if (/paypal\.me/i.test(pp) && a) pp = pp.replace(/\/+$/, "") + "/" + a;
      else if (a) pp += (pp.indexOf("?") > -1 ? "&" : "?") + "amount=" + a;
      out.push({ label: "PayPal", url: pp, qr: pp });
    }
    if (PAY.stripe) out.push({ label: "Card · Stripe", url: PAY.stripe, qr: PAY.stripe });
    return out;
  }
  function renderRails() {
    var box = $("#pay-rails"); box.innerHTML = "";
    var list = rails();
    if (!list.length) { box.appendChild(el("p", "pay-empty", "No paid rails configured yet — leave hearts or a note below.")); return; }
    list.forEach(function (r) {
      var row = el("div", "rail");
      var main = el("div", "rail-main");
      main.appendChild(el("div", "rail-label", r.label));
      var lr = el("div", "rail-linkrow");
      var inp = el("input", "rail-link"); inp.value = r.show || r.url; inp.readOnly = true;
      inp.onclick = function () { inp.select(); };
      var cp = el("button", "rail-copy", "Copy");
      cp.onclick = function () {
        copy(r.url); cp.textContent = "Copied"; cp.classList.add("done");
        setTimeout(function () { cp.textContent = "Copy"; cp.classList.remove("done"); }, 1400);
      };
      lr.appendChild(inp); lr.appendChild(cp); main.appendChild(lr);
      var open = el("a", "rail-open", "Open " + r.label + " ↗");
      open.href = r.url; open.target = "_blank"; open.rel = "noopener";
      open.onclick = function () { if (payItem) logEvent("pay", payItem, payAmount(), r.label); };
      main.appendChild(open);
      row.appendChild(main);
      var qrwrap = el("div", "rail-qr");
      var img = el("img"); img.loading = "lazy"; img.alt = r.label + " QR"; img.src = qr(r.qr);
      qrwrap.appendChild(img); row.appendChild(qrwrap);
      box.appendChild(row);
    });
  }
  function buildPayFoot() {
    var foot = $(".pay-foot"); foot.innerHTML = "";
    if (PAY.hearts !== false) {
      var h = el("button", "btn-ghost", "♥ Pay in hearts (free)");
      h.onclick = function () { giveHeart(); if (payItem) logEvent("pay", payItem, 0, "hearts"); };
      foot.appendChild(h);
    }
    if (PAY.message !== false) {
      var m = el("button", "btn-ghost", "Send a cute message");
      m.onclick = function () { closePay(); openMsg(); };
      foot.appendChild(m);
    }
  }
  function giveHeart() {
    var n = (+localStorage.getItem("ve_hearts") || 0) + 1; localStorage.setItem("ve_hearts", n);
    toast("Thank you ♥  (" + n + " heart" + (n === 1 ? "" : "s") + " given)");
  }
  $("#pay-x").onclick = closePay;
  $("#pay").addEventListener("click", function (e) { if (e.target.id === "pay") closePay(); });

  function copy(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) return navigator.clipboard.writeText(text).then(function () { toast("Link copied"); }, fallbackCopy.bind(null, text));
    fallbackCopy(text);
  }
  function fallbackCopy(text) {
    var t = el("textarea"); t.value = text; t.style.position = "fixed"; t.style.opacity = "0";
    document.body.appendChild(t); t.select(); try { document.execCommand("copy"); toast("Link copied"); } catch (e) {} t.remove();
  }

  /* ── cute message ── */
  function openMsg() { $("#msg-status").textContent = ""; $("#msg-status").className = "acct-msg"; $("#msg-body").value = ""; $("#msg").hidden = false; setTimeout(function () { $("#msg-body").focus(); }, 30); }
  function closeMsg() { $("#msg").hidden = true; }
  $("#msg-x").onclick = closeMsg;
  $("#msg").addEventListener("click", function (e) { if (e.target.id === "msg") closeMsg(); });
  $("#msg-go").onclick = function () {
    var body = ($("#msg-body").value || "").trim(), from = ($("#msg-from").value || "").trim();
    var st = $("#msg-status");
    if (!body) { st.className = "acct-msg err"; st.textContent = "Write a line first ♥"; return; }
    if (!API) { st.className = "acct-msg err"; st.textContent = "Messaging needs the backend configured."; return; }
    st.className = "acct-msg"; st.textContent = "…";
    jsonp({ action: "message", from: from || USER || "anon", body: body, ref: (payItem ? payItem.title : "") })
      .then(function (d) {
        if (d && d.ok) { st.className = "acct-msg ok"; st.textContent = "Sent — thank you ♥"; setTimeout(closeMsg, 900); }
        else { st.className = "acct-msg err"; st.textContent = "Could not send. Try again."; }
      }).catch(function () { st.className = "acct-msg err"; st.textContent = "Network error. Try again."; });
  };

  /* ── accounts ── */
  var acctMode = "in";
  function openAcct(mode) {
    acctMode = mode || "in";
    $("#tab-in").classList.toggle("on", acctMode === "in");
    $("#tab-up").classList.toggle("on", acctMode === "up");
    $("#acct-note").textContent = acctMode === "up"
      ? "No password — pick a unique handle. Your shelf travels with it."
      : "Welcome back. Enter your handle to load your shelf.";
    $("#acct-msg").textContent = ""; $("#acct-msg").className = "acct-msg";
    $("#acct-user").value = ""; $("#acctmodal").hidden = false; setTimeout(function () { $("#acct-user").focus(); }, 30);
  }
  function closeAcct() { $("#acctmodal").hidden = true; }
  $("#acct-x").onclick = closeAcct;
  $("#acctmodal").addEventListener("click", function (e) { if (e.target.id === "acctmodal") closeAcct(); });
  $("#tab-in").onclick = function () { openAcct("in"); };
  $("#tab-up").onclick = function () { openAcct("up"); };
  $("#acct-user").addEventListener("keydown", function (e) { if (e.key === "Enter") $("#acct-go").click(); });
  $("#acct-go").onclick = function () {
    var u = ($("#acct-user").value || "").trim(), msg = $("#acct-msg");
    if (!/^[A-Za-z0-9_.-]{2,40}$/.test(u)) { msg.className = "acct-msg err"; msg.textContent = "2–40 chars: letters, numbers, _ . -"; return; }
    if (!API) { msg.className = "acct-msg err"; msg.textContent = "Accounts need the backend configured."; return; }
    msg.className = "acct-msg"; msg.textContent = "…";
    jsonp({ action: acctMode === "up" ? "signup" : "login", username: u }).then(function (d) {
      if (!d || !d.ok) {
        msg.className = "acct-msg err";
        msg.textContent = d && d.error === "taken" ? "That handle is taken." :
          d && d.error === "nouser" ? "No such handle — create it?" : "Could not sign in.";
        return;
      }
      signIn(d.username || u, d.library || []);
      msg.className = "acct-msg ok"; msg.textContent = "Signed in."; setTimeout(closeAcct, 500);
    }).catch(function () { msg.className = "acct-msg err"; msg.textContent = "Network error. Try again."; });
  };
  function signIn(u, serverLib) {
    var anon = Array.from(LIB);
    USER = u; localStorage.setItem("ve_user", u);
    LIB = new Set(serverLib.concat(anon)); DLS = loadArr(uk("ve_dls_")); READS = loadMap(uk("ve_reads_"));
    persistLib(); renderAcct(); toast("Welcome, @" + u); route();
  }
  function signOut() { USER = ""; localStorage.removeItem("ve_user"); reloadLocal(); renderAcct(); toast("Signed out"); route(); }
  function reloadLocal() { LIB = loadSet(uk("ve_lib_")); DLS = loadArr(uk("ve_dls_")); READS = loadMap(uk("ve_reads_")); }

  function renderAcct() {
    var box = $("#acct"); box.innerHTML = "";
    if (USER) {
      var chip = el("button", "acct-chip", "@" + USER + " ▾");
      var menu = el("div", "acct-menu");
      function mi(label, fn) { var b = el("button", null, label); b.onclick = function () { menu.classList.remove("on"); fn(); }; menu.appendChild(b); }
      mi("My Library (" + LIB.size + ")", function () { go("#/library"); });
      mi("My Downloads", function () { go("#/downloads"); });
      mi("Sign out", signOut);
      chip.onclick = function (e) { e.stopPropagation(); menu.classList.toggle("on"); };
      box.appendChild(chip); box.appendChild(menu);
    } else {
      var b = el("button", "acct-chip", "Sign in"); b.onclick = function () { openAcct("in"); };
      box.appendChild(b);
    }
  }
  document.addEventListener("click", function () { var m = $(".acct-menu"); if (m) m.classList.remove("on"); });

  /* ── activity logging to the sheet ── */
  var ipP = null;
  function getIP() {
    if (!ipP) ipP = fetch("https://api.ipify.org?format=json").then(function (r) { return r.json(); }).then(function (d) { return d.ip; }).catch(function () { return ""; });
    return ipP;
  }
  function logEvent(kind, x, amt, via) {
    if (!API) return;
    getIP().then(function (ip) {
      var p = new URLSearchParams({ action: "log", kind: kind, t: new Date().toISOString(),
        title: x ? x.title : "", file: x ? x.file : "", type: x ? x.type : "", amount: amt || 0,
        currency: CFG.currency || "", via: via || "", ip: ip || "", ref: location.href, user: USER || "" });
      var url = API + (API.indexOf("?") > -1 ? "&" : "?") + p.toString();
      fetch(url, { mode: "no-cors" }).catch(function () { new Image().src = url; });
    });
  }

  /* ── toast ── */
  var tT;
  function toast(m) { var t = $("#toast"); t.textContent = m; t.classList.add("on"); clearTimeout(tT); tT = setTimeout(function () { t.classList.remove("on"); }, 2600); }

  /* ── router ── */
  function go(hash) { if (location.hash === hash) route(); else location.hash = hash; }
  function route() {
    var h = (location.hash || "#/").replace(/^#/, ""), parts = h.split("?");
    var segs = parts[0].split("/").filter(Boolean), query = new URLSearchParams(parts[1] || "");
    setNav(segs[0] || "home", segs[1] || "");
    if (segs[0] === "browse") return viewBrowse(segs[1] || "");
    if (segs[0] === "search") { $("#search").value = query.get("q") || ""; return viewSearch(query.get("q") || ""); }
    if (segs[0] === "library") return viewLibrary();
    if (segs[0] === "downloads") return viewDownloads();
    return viewHome();
  }
  window.addEventListener("hashchange", route);
  function buildNav() {
    var nav = $("#nav"); nav.innerHTML = "";
    function link(label, hash) { var a = el("a", null, label); a.dataset.hash = hash; a.onclick = function () { go(hash); }; nav.appendChild(a); }
    link("Home", "#/"); link("Browse", "#/browse");
    SECTIONS.forEach(function (s) { link(s.label, "#/browse/" + s.key); });
    link("My Library", "#/library"); link("Downloads", "#/downloads");
  }
  function setNav(view, sub) {
    var want = view === "home" ? "#/" : view === "browse" ? (sub ? "#/browse/" + sub : "#/browse") :
      view === "library" ? "#/library" : view === "downloads" ? "#/downloads" : "";
    Array.prototype.forEach.call($("#nav").children, function (a) { a.classList.toggle("on", a.dataset.hash === want); });
  }

  /* ── header search ── */
  var sT;
  function wireSearch() {
    $("#search").addEventListener("input", function (e) {
      var q = e.target.value; clearTimeout(sT);
      sT = setTimeout(function () {
        if (!q.trim()) { if (location.hash.indexOf("#/search") === 0) go("#/"); return; }
        if (location.hash.indexOf("#/search") === 0) viewSearch(q.trim());
        else location.hash = "#/search?q=" + encodeURIComponent(q.trim());
      }, 180);
    });
  }
  document.addEventListener("click", function (e) {
    var a = e.target.closest && e.target.closest("[data-go]");
    if (a) { e.preventDefault(); go(a.getAttribute("href")); }
  });
  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    if (!$("#msg").hidden) return closeMsg();
    if (!$("#pay").hidden) return closePay();
    if (!$("#modal").hidden) return closeModal();
    if (!$("#acctmodal").hidden) return closeAcct();
    if (!$("#reader").hidden) return closeReader();
  });

  /* ── init (after data loads) ── */
  function init(generated) {
    app = $("#app");
    reloadLocal();
    $("#foot-meta").textContent = CAT.length + " publications  ·  updated " +
      (generated || "").slice(0, 10) + "  ·  " + BRAND + " — " + (CFG.tagline || "Truth Takes Time");
    buildNav(); renderAcct(); wireSearch();
    if (USER && API) jsonp({ action: "getlib", username: USER }).then(function (d) {
      if (d && d.ok) { LIB = new Set(d.library.concat(Array.from(LIB))); persistLib(); renderAcct(); if (location.hash.indexOf("#/library") === 0) route(); }
    }).catch(function () {});
    route();
  }
})();
